### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Subtilizer28** [Inadequado4192/awse#1]
Was Zedge removed?

**Comment by Subtilizer28** [comment]
@Inadequado4192

**Comment by Inadequado4192** [comment]
> Was Zedge removed?

Yes

**Comment by Subtilizer28** [comment]
so i tried scrapping "Genshin Impact" from alphacoders and got only 3 pics but there are like 2000+. How can i fix this? @Inadequado4192

**Comment by Inadequado4192** [comment]
> so i tried scrapping "Genshin Impact" from alphacoders and got only 3 pics but there are like 2000+. How can i fix this? @Inadequado4192

Hello, just updated the package to 1.3.0, fixed some bugs. Now the query "Genshin Impact" should find from 30 images.
:)
