### ISSUE TITLE
Getting mobile wallpapers

### ISSUE THREAD

**Issue by Subtilizer28** [Inadequado4192/awse#2]
As zedge was removed, is it possible to scrap the mobile wallpapers in alphacoders? As they also provide mobile wallpapers.

**Comment by Inadequado4192** [comment]
> As zedge was removed, is it possible to scrap the mobile wallpapers in alphacoders? As they also provide mobile wallpapers.
Yes, I can do it for you)

**Comment by Inadequado4192** [comment]
> As zedge was removed, is it possible to scrap the mobile wallpapers in alphacoders? As they also provide mobile wallpapers.

Hello, version **1.4.1** has just been released.
Removed an instance of the class **alphacoders,** but added the space **Alphacoders.**
If you can't find the image, try changing the new value in the **by** parameters, its parameters:  "by sub category" | "by collection".

Also to search for images for phones, change **type** to **Mobile** in the search parameters. 



_Why are you using this package at all? (；一_一)_

**Comment by Subtilizer28** [comment]
Lel Its pretty much useful for my discord bot which focuses on providing anime wallpapers on discord. Btw when I set the parameter pages to 50 on the search "Genshin Impact" only 30 images are scrapped. Am I doing something wrong?

**Comment by Inadequado4192** [comment]
> Lel Its pretty much useful for my discord bot which focuses on providing anime wallpapers on discord. Btw when I set the parameter pages to 50 on the search "Genshin Impact" only 30 images are scrapped. Am I doing something wrong?

If you used this before `1.4.1`, there was a bug, it's fixed now.

Just did `1.4.2`. Did not notice the error :) again :)

**Comment by Subtilizer28** [comment]
Oh that's great. Thanks!!!!
